return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "black",
      "clangd",
      "clang-format",
      "css-lsp",
      "debugpy",
      "delve",
      "dockerfile-language-server",
      "golangci-lint",
      "gopls",
      "html-lsp",
      "isort",
      "stylua",
      "terraform-ls",
      "tflint",
      "typescript-language-server",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "prettier",
      "pylint",
      "pyright",
      "rubocop",
      "ruby-lsp",
      "shfmt",
      "vim-language-server",
      "yamlfmt",
      "yaml-language-server",
    },
  },
}
