local function safe_unmap(mode, key)
  pcall(vim.keymap.del, mode, key)
end

safe_unmap({ "s", "i" }, "<Plug>luasnip-jump-prev")
safe_unmap({ "s", "i" }, "<Plug>luasnip-jump-next")
safe_unmap({ "s", "i" }, "<Plug>luasnip-prev-choice")
safe_unmap({ "s", "i" }, "<Plug>luasnip-next-choice")
safe_unmap({ "s", "i" }, "<Plug>luasnip-expand-snippet")
safe_unmap({ "s", "i" }, "<Plug>luasnip-expand-or-jump")
safe_unmap("!", "<Plug>luasnip-expand-repeat")
safe_unmap("!", "<Plug>luasnip-delete-check")
safe_unmap({ "n", "x" }, "gc")
safe_unmap("n", "gcc")
safe_unmap("i", "<C-W>")
safe_unmap("i", "<C-U>")
safe_unmap("n", "&")
safe_unmap("x", "#")
safe_unmap("x", "*")
